# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\Git\_U2\U2.Suite.Python\Sources\U2.Suite\brandmeister\ui\BmMonitorMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BmMonitorMainWindow(object):
    def setupUi(self, BmMonitorMainWindow):
        BmMonitorMainWindow.setObjectName("BmMonitorMainWindow")
        BmMonitorMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(BmMonitorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        BmMonitorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BmMonitorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BmMonitorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BmMonitorMainWindow)
        self.statusbar.setObjectName("statusbar")
        BmMonitorMainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(BmMonitorMainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(BmMonitorMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStart = QtWidgets.QAction(BmMonitorMainWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(BmMonitorMainWindow)
        self.actionStop.setEnabled(False)
        self.actionStop.setObjectName("actionStop")
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BmMonitorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(BmMonitorMainWindow)

    def retranslateUi(self, BmMonitorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        BmMonitorMainWindow.setWindowTitle(_translate("BmMonitorMainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("BmMonitorMainWindow", "File"))
        self.menuHelp.setTitle(_translate("BmMonitorMainWindow", "Help"))
        self.actionExit.setText(_translate("BmMonitorMainWindow", "Exit"))
        self.actionAbout.setText(_translate("BmMonitorMainWindow", "About"))
        self.actionStart.setText(_translate("BmMonitorMainWindow", "Start"))
        self.actionStop.setText(_translate("BmMonitorMainWindow", "Stop"))
