# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\Git\U2.Suite.Python\U2.Suite.Python\Sources\U2.Suite\logger\ui\LogContentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogContentWindow(object):
    def setupUi(self, LogContentWindow):
        LogContentWindow.setObjectName("LogContentWindow")
        LogContentWindow.resize(590, 431)
        LogContentWindow.setStyleSheet("background-color: rgb(46, 52, 54); color: rgb(211, 215, 207);")
        self.centralwidget = QtWidgets.QWidget(LogContentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableMain = QtWidgets.QTableWidget(self.centralwidget)
        self.tableMain.setGeometry(QtCore.QRect(10, 10, 571, 181))
        self.tableMain.setObjectName("tableMain")
        self.tableMain.setColumnCount(6)
        self.tableMain.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMain.setHorizontalHeaderItem(5, item)
        self.tableFiltered = QtWidgets.QTableWidget(self.centralwidget)
        self.tableFiltered.setGeometry(QtCore.QRect(10, 200, 571, 181))
        self.tableFiltered.setObjectName("tableFiltered")
        self.tableFiltered.setColumnCount(6)
        self.tableFiltered.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiltered.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiltered.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiltered.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiltered.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiltered.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableFiltered.setHorizontalHeaderItem(5, item)
        LogContentWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogContentWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 590, 21))
        self.menubar.setObjectName("menubar")
        LogContentWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogContentWindow)
        self.statusbar.setObjectName("statusbar")
        LogContentWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LogContentWindow)
        QtCore.QMetaObject.connectSlotsByName(LogContentWindow)

    def retranslateUi(self, LogContentWindow):
        _translate = QtCore.QCoreApplication.translate
        LogContentWindow.setWindowTitle(_translate("LogContentWindow", "MainWindow"))
        item = self.tableMain.horizontalHeaderItem(0)
        item.setText(_translate("LogContentWindow", "MM-DD HH:MM"))
        item = self.tableMain.horizontalHeaderItem(1)
        item.setText(_translate("LogContentWindow", "Callsign"))
        item = self.tableMain.horizontalHeaderItem(2)
        item.setText(_translate("LogContentWindow", "Freq"))
        item = self.tableMain.horizontalHeaderItem(3)
        item.setText(_translate("LogContentWindow", "Snt"))
        item = self.tableMain.horizontalHeaderItem(4)
        item.setText(_translate("LogContentWindow", "Rcv"))
        item = self.tableMain.horizontalHeaderItem(5)
        item.setText(_translate("LogContentWindow", "Name"))
        item = self.tableFiltered.horizontalHeaderItem(0)
        item.setText(_translate("LogContentWindow", "MM-DD HH:MM"))
        item = self.tableFiltered.horizontalHeaderItem(1)
        item.setText(_translate("LogContentWindow", "Callsign"))
        item = self.tableFiltered.horizontalHeaderItem(2)
        item.setText(_translate("LogContentWindow", "Freq"))
        item = self.tableFiltered.horizontalHeaderItem(3)
        item.setText(_translate("LogContentWindow", "Snt"))
        item = self.tableFiltered.horizontalHeaderItem(4)
        item.setText(_translate("LogContentWindow", "Rcv"))
        item = self.tableFiltered.horizontalHeaderItem(5)
        item.setText(_translate("LogContentWindow", "Name"))
