# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\Git\_U2\U2.Suite.Python\Sources\U2.Suite\logger\ui\LoggerPreferencesDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoggerPreferencesDialog(object):
    def setupUi(self, LoggerPreferencesDialog):
        LoggerPreferencesDialog.setObjectName("LoggerPreferencesDialog")
        LoggerPreferencesDialog.resize(623, 480)
        LoggerPreferencesDialog.setStyleSheet("background-color: rgb(46, 52, 54); color: rgb(211, 215, 207);")
        self.buttonBox = QtWidgets.QDialogButtonBox(LoggerPreferencesDialog)
        self.buttonBox.setGeometry(QtCore.QRect(260, 430, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(LoggerPreferencesDialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 581, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tabUdpPackets = QtWidgets.QWidget()
        self.tabUdpPackets.setObjectName("tabUdpPackets")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tabUdpPackets)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 20, 541, 321))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabUdpWsjt = QtWidgets.QWidget()
        self.tabUdpWsjt.setObjectName("tabUdpWsjt")
        self.cbAcceptWsjtPackets = QtWidgets.QCheckBox(self.tabUdpWsjt)
        self.cbAcceptWsjtPackets.setGeometry(QtCore.QRect(20, 30, 481, 20))
        self.cbAcceptWsjtPackets.setObjectName("cbAcceptWsjtPackets")
        self.tabWidget_2.addTab(self.tabUdpWsjt, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(False)
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tabWidget.addTab(self.tabUdpPackets, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(LoggerPreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.buttonBox.accepted.connect(LoggerPreferencesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(LoggerPreferencesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoggerPreferencesDialog)

    def retranslateUi(self, LoggerPreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        LoggerPreferencesDialog.setWindowTitle(_translate("LoggerPreferencesDialog", "Dialog"))
        self.cbAcceptWsjtPackets.setText(_translate("LoggerPreferencesDialog", "Accept WSJT-X packets"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabUdpWsjt), _translate("LoggerPreferencesDialog", "WSJT-X"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("LoggerPreferencesDialog", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUdpPackets), _translate("LoggerPreferencesDialog", "UDP packets"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LoggerPreferencesDialog", "Tab 2"))
