# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\Git\U2.Suite.Python\U2.Suite.Python\Sources\U2.Suite\logger\ui\StationInfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StationInfoDialog(object):
    def setupUi(self, StationInfoDialog):
        StationInfoDialog.setObjectName("StationInfoDialog")
        StationInfoDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        StationInfoDialog.resize(400, 97)
        StationInfoDialog.setStyleSheet("background-color: rgb(46, 52, 54); color: rgb(211, 215, 207);")
        StationInfoDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(StationInfoDialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(StationInfoDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 230, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tbCallsign = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbCallsign.setFont(font)
        self.tbCallsign.setObjectName("tbCallsign")
        self.gridLayout.addWidget(self.tbCallsign, 0, 1, 1, 1)
        self.lblCallsign = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblCallsign.setFont(font)
        self.lblCallsign.setObjectName("lblCallsign")
        self.gridLayout.addWidget(self.lblCallsign, 0, 0, 1, 1)
        self.lblOperatorName = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblOperatorName.setFont(font)
        self.lblOperatorName.setObjectName("lblOperatorName")
        self.gridLayout.addWidget(self.lblOperatorName, 1, 0, 1, 1)
        self.tbCallsign_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbCallsign_2.setFont(font)
        self.tbCallsign_2.setObjectName("tbCallsign_2")
        self.gridLayout.addWidget(self.tbCallsign_2, 1, 1, 1, 1)

        self.retranslateUi(StationInfoDialog)
        self.buttonBox.accepted.connect(StationInfoDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(StationInfoDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StationInfoDialog)

    def retranslateUi(self, StationInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        StationInfoDialog.setWindowTitle(_translate("StationInfoDialog", "Dialog"))
        self.lblCallsign.setText(_translate("StationInfoDialog", "Callsign"))
        self.lblOperatorName.setText(_translate("StationInfoDialog", "Operator"))
